name: Update dependencies

on:
  schedule:
    - cron: '0 0 * * *'
  repository_dispatch:
    types: [update-dependencies]

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - id: commit
        uses: pr-mpt/actions-commit-hash@v2

      - name: Checkout project
        uses: actions/checkout@v2
        with:
          ref: rc
          token: ${{ secrets.PAT }}

      - name: Install dependencies
        run: composer install --no-scripts --no-progress

      - name: Update dependencies
        run: composer require sergeyspryker/randomizer --no-scripts --no-progress

      - name: Commit, push and create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          title: Updated Randomizer
          body: |
            This pull request updates sergeyspryker/randomizer dependency to the latest version.
          commit-message: Updated randomizer dependency
          committer: GitHub <depbot@example.test>
          author: ${{ github.actor }} <${{ github.actor }}@example.test>
          base: rc
          branch: update-dependencies
          branch-suffix: short-commit-hash
          token: ${{ secrets.PAT }}
          labels: composer dependencies
          delete-branch: true
          assignees: sergeyspryker
          reviewers: sergeyspryker
