name: Update dependencies

on:
  schedule:
    - cron: '0 0 * * *'
  repository_dispatch:
    types: [update-dependencies]

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - id: commit
        uses: pr-mpt/actions-commit-hash@v2

      - name: Checkout project
        uses: actions/checkout@v2
        with:
          ref: main
          token: ${{ secrets.PAT }}

      - name: Install dependencies
        run: composer install --no-scripts --no-progress

      - name: Update dependencies
        run: composer require pavelmaksimov25/randomizer --no-scripts --no-progress

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated randomizer
          commit_options: '--no-verify --signoff'
          branch: update-dependencies-${{ steps.commit.outputs.short }}
          create_branch: true

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          title: Updated Randomizer
          body: |
            This pull request updates the dependencies of repository B based on the latest version of repository A.
          commit-message: Updated randomizer dependency
          branch: update-dependencies-${{ steps.commit.outputs.short }}
          token: ${{ secrets.PAT }}
