name: Update dependencies

on:
  repository_dispatch:
    types: [ EXTERNAL_TRIGGER_EVENT ]

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - id: commit
        uses: pr-mpt/actions-commit-hash@v2

      - name: Checkout project
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Install dependencies
        run: composer install --no-scripts --no-progress

      - name: Update dependencies
        run: composer require sergeyspryker/from --no-scripts --no-progress

      - name: Commit, push and create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          title: Updated Randomizer
          body: |
            This pull request updates sergeyspryker/from dependency to the latest version.
          commit-message: Updated randomizer dependency
          committer: GitHub <depbot@example.test>
          author: ${{ github.actor }} <${{ github.actor }}@example.test>
          base: main
          branch: update-dependencies
          branch-suffix: short-commit-hash
          labels: composer dependencies
          delete-branch: true
          assignees: sergeyspryker
          reviewers: sergeyspryker
