name: Update dependencies

on:
  repository_dispatch:
    types: [ dependency_updated ]

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    env:
      TARGET_BRANCH: main
      PR_ASSIGNEES: sergeyspryker
      PR_REVIEWERS: sergeyspryker
      DEPENDENCY: sergeyspryker/from
    steps:
      - id: commit
        uses: pr-mpt/actions-commit-hash@v2

      - name: Checkout project
        uses: actions/checkout@v3
        with:
          ref: env.TARGET_BRANCH

      - name: Update dependencies
        run: composer require sergeyspryker/from --no-scripts --no-progress --no-install

      - name: Commit, push and create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          title: Updated Randomizer
          body: |
            This pull request updates sergeyspryker/from dependency to the latest version.
          commit-message: Updated dependencies
          committer: SprykerReleaseBot <spryker-release-bot@spryker.com>
          author: ${{ github.actor }} <${{ github.actor }}@example.test>
          base: env.TARGET_BRANCH
          branch: update-dependencies
          branch-suffix: timestamp
          labels: composer dependencies
          delete-branch: true
          assignees: sergeyspryker
          reviewers: sergeyspryker
