name: Sync
on:
  push:
    branches:
      - main

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
    - id: commit
      uses: pr-mpt/actions-commit-hash@v2

    - name: Checkout project
      uses: actions/checkout@v2
      with:
        ref: rc
        token: ${{ secrets.PAT }}

    - name: Opening pull request
      id: pull
      uses: tretuna/sync-branches@1.4.0
      with:
        GITHUB_TOKEN: ${{secrets.PAT}}
        FROM_BRANCH: "main"
        TO_BRANCH: "rc"
        REVIEWERS: pavelmaksimov25
